†追加† ヘッダー(not レスポンシブ)ができた
brokenManager/devlaza-front pull request #1
Opened 2020-03-25 14:45 UTC by loxygenK

できました、可能であればテストを頼みたい(嘆願)
```
yarn start
```

2020-03-25 19:05 UTC, kawaemon requested changes
プロジェクトに参加してない身で勝手にレビューしてすみません、、、
テストしたところ、2点問題がありましたので、報告させていただきます。

2020-03-25 19:05 UTC, kawaemon commented on src/comp/Header.tsx
> +	}
この警告を防ぐために必要です。
```
Warning: Header(...): When calling super() in `Header`, make sure to pass up the same props that your component's constructor was passed.
    in Header (at App.tsx:8)
    in div (at App.tsx:7)
    in App (at src/index.tsx:9)
    in StrictMode (at src/index.tsx:8)
```
```suggestion
type HeaderProps = {}

class Header extends React.Component<HeaderProps, HeaderState> {
	constructor(props: HeaderProps){
		super(props);
		this.state = {
			searchbox: ""
		}
	}
```

2020-03-25 19:05 UTC, kawaemon commented on public/index.html
> +		<link rel="stylesheet" href="%PUBLIC_URL%/fontawesome-free-5.13.0-web/css/all.css">
FontAwesomeのロードに失敗しています。
以下はChromeに表示された警告です。
```
Failed to decode downloaded font: http://localhost:3000/fontawesome-free-5.13.0-web/webfonts/fa-solid-900.woff2
OTS parsing error: invalid version tag
Failed to decode downloaded font: http://localhost:3000/fontawesome-free-5.13.0-web/webfonts/fa-solid-900.woff
OTS parsing error: invalid version tag
Failed to decode downloaded font: http://localhost:3000/fontawesome-free-5.13.0-web/webfonts/fa-solid-900.ttf
OTS parsing error: invalid version tag
```
もっとも簡単な解決方法としては、npmにあるfontawesomeのreact用パッケージを使う方法です。
https://github.com/FortAwesome/react-fontawesome
を参照してください。
これをすることで、Header.tsxの`<i className="fas fa-search" />`が`<FontAwesomeIcon icon={faSearch} />`になり、可読性も増すと思います。

2020-03-26 03:29 UTC, loxygenK commented on src/comp/Header.tsx
> +	}
ありがとうございます！suggestionをcommitしておきました。

2020-03-26 04:01 UTC, loxygenK commented on public/index.html
> +		<link rel="stylesheet" href="%PUBLIC_URL%/fontawesome-free-5.13.0-web/css/all.css">
2928877 で適用しました、ありがとうございます！

2020-03-26 04:02 UTC, loxygenK commented
レビューありがとうございます！修正を加えたので良ければ再度レビューしていただけると幸いです！

2020-03-26 07:18 UTC, kawaemon commented on public/index.html
> +		<link rel="stylesheet" href="%PUBLIC_URL%/fontawesome-free-5.13.0-web/css/all.css">
npmパッケージからのロードに変更したので、この部分はもう必要ありません。
```suggestion
```

2020-03-26 07:18 UTC, kawaemon commented on src/comp/Header.css
> +.header-btn {
これは提案ですが、ヘッダーボタンのテキストをドラッグして選択できないようにするのはどうでしょうか。今回のようなボタンの配置とHTMLの配置が逆になっている状態だと、ドラッグするとテキスト選択が変な挙動をします。

2020-03-26 08:33 UTC, loxygenK commented on public/index.html
> +		<link rel="stylesheet" href="%PUBLIC_URL%/fontawesome-free-5.13.0-web/css/all.css">
あっ！？消し忘れていました、ありがとうございます！

2020-03-26 08:53 UTC, loxygenK commented on src/comp/Header.css
> +.header-btn {
7cb334a で修正しました。今知りました、ありがとうございます！

2020-03-26 09:02 UTC, kawaemon approved these changes
後は私からは特にありません。素晴らしいデザインだと思います :+1::+1::+1:

2020-03-26 09:04 UTC, kawaemon commented
あとどうでもいいんですけど、PRマージする時はsquashしたほうがHistoryが見やすくなっていいと思います。(このブランチでの変更が1コミットにまとめられてからマージされます）
Merge pull requestの右の矢印から選択できますので、参考にどうぞ。

2020-03-26 09:11 UTC, kawaemon commented on public/index.html
> +		<link rel="stylesheet" href="%PUBLIC_URL%/fontawesome-free-5.13.0-web/css/all.css">
`public/fontawesome...`ディレクトリも消して大丈夫だと思います

2020-03-26 11:48 UTC, loxygenK commented on public/index.html
> +		<link rel="stylesheet" href="%PUBLIC_URL%/fontawesome-free-5.13.0-web/css/all.css">
（失念が重なり絶望する音）

2020-03-26 11:52 UTC, loxygenK commented on public/index.html
> +		<link rel="stylesheet" href="%PUBLIC_URL%/fontawesome-free-5.13.0-web/css/all.css">
対応したのでResolveしてしまいます

2020-03-26 11:53 UTC, loxygenK commented
レビューしていただきありがとうございました！よろしければこれからもよろしくお願いします。

2020-03-26 12:13 UTC, isso0424 approved these changes
† ***approve*** †

2020-03-26 12:13 UTC, loxygenK commented
多くの世界すまんをしましたが***Squashをして***mergeをします

2020-03-26 12:14 UTC, merged