Edit style
brokenManager/devlaza-front pull request #20
Opened 2020-04-07 11:03 UTC by unios103

# 変更点について

- CSSファイルを`src/css`以下に移動しました。

- `typed-css-modules`を放り込んだので、拡張子、importの書き方等、色々変更しています。以下のリンク先にまとめて書きました。
 [CSS関連の変更点について - README.md](https://github.com/unios103/devlaza-front/blob/editStyle/src/css/README.md)

- Headerのメニューボタン、Footerのリストは`data`の内容を編集すれば変更できるようにしました。

``` ts
// 例↓
const data: footerList = {
  list: [
	// 以下を編集
    {
      title: "プロジェクトを探す",
      contents: ["人気プロジェクト", "条件を指定して検索"],
    },
  ],
};
```

- 主なデザインは変更していませんが、ボタンの色やリンクの色をヘッダーやフッターの色に合わせて一部変更しています。

- フォントやpadding、marginを指定する単位を変更しています。(px -> rem, vh 等)

- HeaderとFooterはレスポンシブになってます。（多分）

  - Header : 画面の横幅が小さくなるにつれてメニューボタンと検索部分がドロワーの中に移動します。
  - Footer : サイズに合わせて並び替えられます。

**画面の横幅が小さくなったときの例↓**

<details><summary>ドロワー</summary><div>

 ![Header image](https://user-images.githubusercontent.com/55628112/78659113-0e9a9d80-7906-11ea-8065-18da1fa78094.jpeg)

</details>

<details><summary>フッター</summary><div>

 ![Footer image](https://user-images.githubusercontent.com/55628112/78659147-1b1ef600-7906-11ea-823c-e48a50873024.jpeg)

</details>

2020-04-07 15:23 UTC, loxygenK requested changes
すごい様々なことをしてもらっていて、ありがたさで爆発しているんですが、
ひとつだけエラーが見つかったので確認お願いします

ありがとうございます！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！１１１

2020-04-07 15:23 UTC, loxygenK commented on src/comp/Header.tsx
> +        handleSearchBoxChange={this.handleSearchBoxChange}
```suggestion
        handleSearchBoxChange={this.handleSearchBoxChange.bind(this)}
```
検索ボックスの値を変更したときにエラーがでてつらいです

2020-04-07 15:23 UTC, loxygenK commented on src/comp/Header.tsx
> +          handleSearchBoxChange={this.handleSearchBoxChange}
```suggestion
          handleSearchBoxChange={this.handleSearchBoxChange.bind(this)}
```

2020-04-07 23:46 UTC, kawaemon commented on src/comp/Header.tsx
> +          handleSearchBoxChange={this.handleSearchBoxChange}
そもそもConstructorにこうやって書いとくと、`handleSearchBoxChange={this.handleSearchBoxChange}`って書いても問題なくなるのでこっちのほうがおすすめ

```
    this.handleSearchBoxChange.bind(this);
    this.handleResize.bind(this);
    this.changeMenuListStatus.bind(this);
```

2020-04-07 23:57 UTC, kawaemon requested changes

2020-04-07 23:57 UTC, kawaemon commented on src/comp/Header.tsx
> +  handleResize = () => {
ラムダ式スタイル`const handleResize = () => {}`と、function宣言使う方式`handleSearchBoxChange(...) {`が混在してるので、統一しませんか、、、？

2020-04-07 23:57 UTC, kawaemon commented on src/comp/Header.tsx
> +    }
```suggestion
    this.setState({ moveSearchContents: window.innerWidth <= 544 });
```

2020-04-07 23:57 UTC, kawaemon commented on src/comp/Header.tsx
> +      moveSearchContents: window.innerWidth <= 544 ? true : false,
```suggestion
      showMenuIcon: window.innerWidth <= 970,
      showMenuList: false,
      moveSearchContents: window.innerWidth <= 544,
```

2020-04-07 23:57 UTC, kawaemon commented on src/comp/Header.tsx
> +      </React.Fragment>
```suggestion
      <>
        <EventListener target="window" onResize={this.handleResize} />
        <AppBar color="secondary">
          <Toolbar className={styles.header}>
            <div className={styles.header_contents_box}>
              <div className={styles.header_logo}>Devlaza</div>
              {searchContent}
            </div>
            {menuContents}
          </Toolbar>
        </AppBar>
        <Toolbar />
        <Drawer
          anchor={"right"}
          open={this.state.showMenuList}
          onClose={() => this.changeMenuListStatus(false)}
        >
          <Paper className={styles.paper}>{menuButtonList}</Paper>
        </Drawer>
      </>
```

2020-04-07 23:57 UTC, kawaemon commented on src/comp/menuContents.tsx
> +    </React.Fragment>
```suggestion
    <>
      {buttonData.button.map((value: contents, index: number) => {
        return (
          <Button
            key={index}
            startIcon={value.icon}
            color="secondary"
            className={styles.header_btn}
            style={style}
          >
            {value.name}
          </Button>
        );
      })}
    </>
```

2020-04-07 23:57 UTC, kawaemon commented on src/comp/menuContents.tsx
> +    </React.Fragment>
他にもいっぱい<React.Fragment>を使ってるところがありますが、全部<> </>で省略できるので、こっち方法がいいと思います。

2020-04-08 04:03 UTC, unios103 commented
- 




- loxygenKさんが言っていたエラーは`handleSearchBoxChange=(...)=>{}`こう書き換えたら直りました。

- かわえもんに指摘された点(React.Fragment,ウィンドウサイズの判定部分等)を修正しました。

- このエラーの原因がわかりません。

<details><summary>エラーのスクショ</summary><div>

 ![エラー](https://user-images.githubusercontent.com/55628112/78743148-bf517d00-7998-11ea-9985-78667d1ba4e4.jpeg)

</details>

2020-04-08 04:44 UTC, unios103 commented on src/comp/Header.tsx
> +  handleResize = () => {
統一したらエラーが消え去ったので神

2020-04-08 05:40 UTC, kawaemon commented
問題のエラーは、Material-ui側のバグだそうです。
https://github.com/mui-org/material-ui/issues/13394
Version5で治るらしい（今は4.9.8)ので、放置しかなさそう

2020-04-08 05:41 UTC, unios103 commented
放置します

2020-04-08 10:30 UTC, unios103 commented
`.d.ts`ファイルのダブルクォーテーションがlintに怒られたので`yarn fix`しました、、、

2020-04-08 11:33 UTC, unios103 commented on src/comp/Header.tsx
> +          handleSearchBoxChange={this.handleSearchBoxChange}
`handleSearchBoxChange=(...)=>{}`に統一しました。

2020-04-08 11:52 UTC, loxygenK approved these changes
***†Approve†***

2020-04-08 14:35 UTC, kawaemon approved these changes
いいとおもいます

2020-04-08 14:52 UTC, merged