ユーザー詳細ページ作った
brokenManager/devlaza-front pull request #37
Opened 2020-04-19 13:07 UTC by unios103

使ってるデータは***適当***です

<details><summary>PCの時</summary><div>

 ![PC](https://user-images.githubusercontent.com/55628112/79688479-90d17d00-8289-11ea-89e7-929787870d14.jpeg)

</details>

<details><summary>スマホの時 1</summary><div>

 ![スマホ](https://user-images.githubusercontent.com/55628112/79688481-929b4080-8289-11ea-8d29-ec6a9f0594c0.jpeg)

</details>

<details><summary>スマホの時 2</summary><div>

![](https://user-images.githubusercontent.com/55628112/79688484-94fd9a80-8289-11ea-946c-1464b1982db7.jpeg)

</details>

2020-04-19 13:53 UTC, loxygenK approved these changes
天才です！！！！！！！！ありがとうございます！！！！！！！！！！！！！！！！！！！！ ***†Approve†*** ！！！！！！！！！！！！！！！！
一つお聞きしたいのがフォローボタンなんですが、フォローしてるときは背景色を塗りつぶす(Twitterのそれみたいな感じ)ってできませんかね…?

2020-04-19 13:53 UTC, loxygenK commented on src/comp/FollowButton.tsx
> +      </Button>
```suggestion
    return (
      <Button
        size="small"
        variant="outlined"
        className={styles.buttonContentsWrapper}
        color="secondary"
        onClick={() => changeFollowingState()}
      >
        <p>{followingState.isFollowing ? "Unfollow" : "follow"}</p>
      </Button>
```
これは圧倒的 ***†おせっかい†*** なんですが、これをすると世界が平和になります

2020-04-19 14:07 UTC, kawaemon requested changes
現在レビュー中です。ただ100%このままでは通らないので一回RequestChangesしておきます

2020-04-19 14:08 UTC, kawaemon commented on src/App.tsx
> +  loginUserFollowingIdList: number[];
命名なんとかしましょう。
```suggestion
  UserFollowingIdList: number[];
```
とか

2020-04-19 14:30 UTC, isso0424 requested changes
***†REQUEST CHANGES†***
ウンコーダーの感想なので間違っている可能性はあります

2020-04-19 14:30 UTC, isso0424 commented on src/comp/UserDetailsComponent.tsx
> +      </div>
comp2つにしませう

2020-04-19 14:30 UTC, isso0424 commented on src/comp/pages/CreateProjectPage.tsx
> +type CreateProjectPageProps = RouteComponentProps;
RouteComponentPropsを直接渡しませんか

2020-04-19 14:30 UTC, isso0424 commented on src/comp/pages/CreateProjectPage.tsx
> +    }
三項演算子の使いどきですよ!

2020-04-19 14:30 UTC, isso0424 commented on src/comp/pages/CreateProjectPage.tsx
> +    if (ableSendFlag) {
ableSendFlag => ableSend
ableSend => ableSendButton
disableSend => diableSendButton

2020-04-19 14:30 UTC, isso0424 commented on src/comp/pages/CreateProjectPage.tsx
> +  changeButtonType = () => {
createSendButtonとかどうですか

2020-04-19 14:30 UTC, isso0424 commented on src/comp/pages/CreateProjectPage.tsx
>              </div>
comp分けません?

2020-04-19 14:30 UTC, isso0424 commented on src/App.tsx
> +  };
こいつはFollowButtonにはやそうね

2020-04-19 14:30 UTC, isso0424 commented on src/comp/pages/UserDetailsPage.tsx
> +            </div>
compいくつかに分けれませんか()

2020-04-19 14:30 UTC, isso0424 commented on src/comp/pages/UserDetailsPage.tsx
> +            </div>
というかスマホとpcでcomp分けてしまえばいいのでは

2020-04-19 14:38 UTC, MikuroXina requested changes
CSS モジュールはあまり詳しくないので TypeScript を中心にレビューしておきました

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +
これは別ファイルにコンポーネントとして分けてください

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +  };
これはただの関数としてクラス外においてください
また、これはそのまま `boolean` を返してください
```suggestion
  checkBlankSpace = (value: string) => {
    return !value.match(/\S/g);
  };
```

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/pages/UserDetailsPage.tsx
> +
型定義は `PascalCase` を推奨します
`camelCase` では変数名と紛らわしくなります

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/pages/UserDetailsPage.tsx
> +  };
別ファイルにコンポーネントとして分けてください

2020-04-19 14:38 UTC, MikuroXina commented on src/App.tsx
> +  };
このような処理は画面でやらずに、別ファイルに `FollowingIdList` のようなクラスを作って、そこで行ってください
他の画面でやってる ID のリストに対する処理も、そのクラスに閉じ込めてください

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/pages/UserDetailsPage.tsx
> +                updateFollowingList={this.props.updateFollowingList}
`props` の関数を直接渡さずに、一度関数を作り直して結合度を弱めてください
```suggestion
                updateFollowingList={(index, id) => this.props.updateFollowingList(index, id)}
```

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/FollowButton.tsx
> +  };
この書き方だと状態を持ってる意味がないです
`updateFollowingList` を呼び出したことで親コンポーネントの状態にあるリストが更新されると、
このコンポーネントは破棄されて再構築されます
なので `changeState` が呼び出されることはありません

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/FollowButton.tsx
> +  };
`filter` を使って `id` が同じものを抽出しましょう

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/FollowButton.tsx
> +  return <>{buttonContents()}</>;
これはわざわざ関数に分けずに、そのまま地の文で書いていいです

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/UserDetailsComponent.tsx
> +  };
ただの関数として外に置いてください
また、`birthDay` の型を `number` にせずに、`Birthday` などのクラスにすることも検討してください

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/UserDetailsComponent.tsx
> +  };
ただの関数として外に置いてください

2020-04-19 14:38 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +    }
冗長な `else` なので消してください
(人によっては `? :` を使えと言うかもしれませんが、私は別に `if` でいいです)
```suggestion
    return disableSend;
```

2020-04-19 14:44 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +    if (ableSendFlag) {
`ableSendFlag` => `canSend`
`ableSend` => `enabledButton`
`disableSend` => `disabledButton`
の方がいいと思います

2020-04-19 14:50 UTC, kawaemon requested changes
つよくいきて

2020-04-19 14:50 UTC, kawaemon commented on src/App.tsx
> +    const { loginUserFollowingIdList } = this.state;
```suggestion
    const List = this.state.loginUserFollowingIdList;
```

ではいけませんか

2020-04-19 14:50 UTC, kawaemon commented on src/comp/DevExperience.tsx
> +  };
関数オブジェクトにする意味ない気がします。一箇所でしか使われてないし、中身がたかが1行なので

2020-04-19 14:50 UTC, kawaemon commented on src/comp/DevExperience.tsx
> +        })}
省略できます
```suggestion
        {tagList.map((tag: string, i: number) => (
            <Chip
              className={styles.chip}
              variant="outlined"
              size="small"
              label={tag}
              key={i}
            />
          ))}
```

2020-04-19 14:50 UTC, kawaemon commented on src/comp/DevExperience.tsx
> +    if (introduction.length > 80) {
80をconstして外に出しませんか

2020-04-19 14:50 UTC, kawaemon commented on src/comp/DevExperience.tsx
> +          return (
returnを外して省略できます

2020-04-19 14:50 UTC, kawaemon commented on src/comp/DevExperience.tsx
> +      {returnDevProjectList(projectDataList)}
これ関数オブジェクトにしなくていい気がします。。。

2020-04-19 14:50 UTC, kawaemon commented on src/comp/FollowButton.tsx
> +  const buttonContents = () => {
これ関数オブジェクトにしなくて良くないですか

2020-04-19 14:50 UTC, kawaemon commented on src/comp/UserDetailsComponent.tsx
> +  birthDay: number;
数字で管理するのは非常によろしくない、、クラスとかtypeとかにしましょう、、

2020-04-19 14:50 UTC, kawaemon commented on src/comp/pages/UserDetailsPage.tsx
> +        )}
不要なコメントの削除と、三項演算子をなんとかしてください。可読性。。。

2020-04-19 15:06 UTC, mirror-kt requested changes

2020-04-19 15:06 UTC, mirror-kt commented on src/App.tsx
> +class App extends React.Component<{}, AppStatus> {
空のPropsを定義してからComponentの型引数に渡すべき？
```suggestion
type AppProps = {}

class App extends React.Component<{}, AppStatus> {
```

2020-04-19 15:06 UTC, mirror-kt commented on src/App.tsx
> +  constructor(props: {}) {
```suggestion
  constructor(props: AppProps) {
```

2020-04-20 12:33 UTC, MikuroXina requested changes
こちら、追加注文の品です

2020-04-20 12:33 UTC, MikuroXina commented on src/comp/SendButton.tsx
> +};
このボタンの役割は、
- このボタンがが押されたらそれを呼び出す

だけにするべきです

`RouteComponentProps` を受け取るのではなく、
必要な操作の関数 (この場合は「ボタンが押されたことを通知する」関数) を受け取ってください

値が正しいかどうかの確認はここではなく外側で行い、`SendButtonProps` で有効化されているかどうかを受け取ってください

2020-04-20 12:33 UTC, MikuroXina commented on src/comp/pages/UserDetailsPage.tsx
> +      contentment: {
```suggestion
      content: {
```
`contentment` (満足、成就) ではなく `content` (内容) ではないですか

2020-04-20 13:05 UTC, MikuroXina approved these changes
大丈夫……だと思う

2020-04-20 14:09 UTC, loxygenK reviewed
知識のないウンコーダーなりにお気持ち表明を執り行ってみました
「こいつ何言ってんだ？？？」ってのがあったら流してください🙇‍♀️

2020-04-20 14:09 UTC, loxygenK commented on src/App.tsx
> +    if (followingIndex === -1) {
```suggestion
  updateFollowingList = (userId: number) => {
    const list = this.state.loginUserFollowingIdList;
    const followingIndex = list.indexOf(userId);
    if (followingIndex === -1) {
```
適用したあとの変更がちょっとめんどくさいですがこれをすればfollowingIndex引数が必要なくなります

2020-04-20 14:09 UTC, loxygenK commented on src/comp/pages/UserDetailsPage.tsx
> +    return followInfo;
```suggestion
    const followingIndex = this.props.loginUserFollowingIdList.indexOf(
      this.state.userId
    );
    return { isFollow: followingIndex !== -1, followIndex: followingIndex };
```
`forEach`使わなくても配列の検索できます

2020-04-20 14:09 UTC, loxygenK commented on src/comp/pages/UserDetailsPage.tsx
> +              ></img>
```suggestion
              />
```

2020-04-20 14:09 UTC, loxygenK commented on src/comp/DevExperience.tsx
> +      {projectData().map((projectDetails: projectDataType, i: number) => (
圧倒的好みの問題だと思うんですが、
一つの`DevExperience`コンポーネントでいっぱいプロジェクトを表示させるんじゃなくて、
`UserDetailsPage.tsx`内でプロジェクトの配列をぐるぐる回して`DevExperience`をいっぱい発生させたいお気持ちが強い、どうですか?
世界を混沌に陥れられるくらいには説明が下手なので、補足の図を置いておきます…
![image](https://user-images.githubusercontent.com/55672846/79759986-5be12b00-835a-11ea-8743-7036cf09287c.png)

2020-04-20 14:09 UTC, loxygenK commented on src/comp/UserDetailsComponent.tsx
> +const changeDisplayStyle = (numberOfFollow: number) => {
`simplifyNumberStyle` (数の表記を単純にする) とかじゃだめですかね…?

2020-04-20 14:16 UTC, unios103 commented on src/comp/DevExperience.tsx
> +      {projectData().map((projectDetails: projectDataType, i: number) => (
レイアウトの問題でですね、それをすると`src/comp/pages/UserDetailsPage.tsx`が***混沌の世界***と化するので、はい、あの、ぼくが悪いんですけど、ごめんなさい、、、

2020-04-20 14:17 UTC, MikuroXina commented on src/App.tsx
> +    if (followingIndex === -1) {
本当はなんらかの ID でやりとりするべきなので、インデックスに固めるのはまずいと思います

2020-04-20 14:20 UTC, loxygenK commented on src/comp/DevExperience.tsx
> +      {projectData().map((projectDetails: projectDataType, i: number) => (
ああなるほど…わかりました

2020-04-20 14:21 UTC, unios103 commented on src/comp/pages/UserDetailsPage.tsx
> +    return followInfo;
天才

2020-04-20 14:21 UTC, MikuroXina commented on src/comp/DevExperience.tsx
> +      {projectData().map((projectDetails: projectDataType, i: number) => (
参考実装置いときます
```tsx
const DevExperience: FC<{ children: ReactNode[] }> = ({ children }) => {
  // いろいろ
  return <>
    {children}   
  </>
}
// ↑ はこう使う
<DevExperience>
  <Nanya />
  <Kanya />
</DevExperience>
```

2020-04-20 14:25 UTC, loxygenK commented on src/App.tsx
> +    if (followingIndex === -1) {
インデックスに固める…というのはどういうことでしょうか?

2020-04-20 14:44 UTC, MikuroXina commented on src/App.tsx
> +    if (followingIndex === -1) {
後々 ID を使ったものに変更しづらくなるっていうことです

2020-04-20 14:50 UTC, loxygenK commented on src/App.tsx
> +    if (followingIndex === -1) {
あああなるほど理解しました！！！！！
そしたら今後のためにこのままResolvedにすべきですか？

2020-04-21 07:23 UTC, kawaemon approved these changes
だいぶ良くなったんじゃないでしょうか

2020-04-21 07:23 UTC, kawaemon commented on src/comp/FollowButton.tsx
> +    return <p>{followButtonText}</p>;
細かいんですが、変数に入れなくても良くないですか
```suggestion
    if (isFollow) {
      return <p>Unfollow</p>
    }
    return <p>Follow</p>;
```

2020-04-21 07:35 UTC, MikuroXina commented on src/App.tsx
> +    if (followingIndex === -1) {
まあフォロー/フォロー解除のボタン押下時の処理にインデックスが必要なのもおかしいですし、
`followingIndex` が `-1` かどうかで動作を変えていたりとなかなか怪しいので、
今のうちに `follow(userIdToFollow)` と `unfollow(userIdToUnfollow)` に分けた方がいいと思います

2020-04-21 07:38 UTC, loxygenK commented on src/App.tsx
> +    if (followingIndex === -1) {
確かに関数分けたほうが良さそうですね

@unios103 だそうです🙇‍♀️

2020-04-21 08:25 UTC, unios103 commented
ほんまか？

2020-04-21 15:19 UTC, isso0424 requested changes
***REQUEST CHANGES***

2020-04-21 15:19 UTC, isso0424 commented on src/App.tsx
> +  userIdUnfollow = (userId: number) => {
`userIdToUnfollow`

2020-04-21 15:19 UTC, isso0424 commented on src/comp/AccountLink.tsx
> +      accountName: keyof AccountType | keyof AccountTypeOfElement,
accountTypeにしませんか
これアカウント名っぽく見える

2020-04-21 15:19 UTC, isso0424 commented on src/comp/AccountLink.tsx
> +          {props.isPhone ? <></> : <p>{accounts[accountName]}</p>}
`accounts[accountName]`って先に取り出せませんか

2020-04-21 15:19 UTC, isso0424 commented on src/comp/AccountLink.tsx
> +  const accounts: AccountType = props.accounts;
linkedAccountsとかにしませんか()

2020-04-21 15:19 UTC, isso0424 commented on src/comp/FollowButton.tsx
> +      {buttonContents(props.isFollow)}
三項演算子の使いどきですが

2020-04-21 15:19 UTC, isso0424 commented on src/comp/pages/CreateProjectPage.tsx
> +};
`() => value`してください

2020-04-21 15:19 UTC, isso0424 commented on src/comp/pages/UserDetailsPage.tsx
> +    }
```suggestion
	let phoneElement: JSX.Element;
	let pcElement: JSX.Element;

	if (this.state.isPhone) {
	  phoneElement = element.content;
	  pcElement = element.empty;
	} else {
	  pcElement = element.content;
	  phoneElement = element.empty;
	}
```

これではいかんのか

2020-04-21 15:19 UTC, isso0424 commented on src/comp/pages/UserDetailsPage.tsx
> +    };
これは`insertContent`と`empty`っていう2つの変数にしませんか
これはオブジェクトにする意味が無いはず

2020-04-21 15:19 UTC, isso0424 commented on src/comp/AccountLink.tsx
> +      accountName: keyof AccountType | keyof AccountTypeOfElement,
`record`使えばこれunionである意味無いが

2020-04-21 15:19 UTC, isso0424 commented on src/comp/AccountLink.tsx
> +  showList: Array<keyof AccountType>;
`linkedAccountsList`ってどうですか

2020-04-21 15:19 UTC, isso0424 commented on src/comp/DevExperience.tsx
> +type projectDataListType = projectDataType[];
いらない

2020-04-22 06:02 UTC, unios103 commented on src/comp/AccountLink.tsx
> +      accountName: keyof AccountType | keyof AccountTypeOfElement,
`accountKey: keyof AccountType`

2020-04-22 06:02 UTC, unios103 commented on src/comp/AccountLink.tsx
> +      accountName: keyof AccountType | keyof AccountTypeOfElement,
TypeじゃないからaccountKeyにした

2020-04-22 06:37 UTC, MikuroXina requested changes
さらに追加

2020-04-22 06:37 UTC, MikuroXina commented on src/comp/FollowButton.tsx
> +      {props.isFollow ? <p>UnFollow</p> : <p>Follow</p>}
`isFollow` が `true` のときに Unfollow なのはおかしいと思います
この `FollowButton` を使う側で渡している値をチェックしてください

2020-04-22 06:38 UTC, MikuroXina commented on src/comp/FollowButton.tsx
> +      {props.isFollow ? <p>UnFollow</p> : <p>Follow</p>}
というか、「これからフォローする」のか「このボタンはフォローするボタンにする」のかはっきりした名前にしてください

2020-04-22 06:42 UTC, unios103 commented on src/comp/FollowButton.tsx
> +      {props.isFollow ? <p>UnFollow</p> : <p>Follow</p>}
フォローするボタンなのでfollow buttonです

2020-04-22 06:43 UTC, MikuroXina commented on src/comp/FollowButton.tsx
> +      {props.isFollow ? <p>UnFollow</p> : <p>Follow</p>}
```suggestion
      {props.isFollowing ? <p>UnFollow</p> : <p>Follow</p>}
```

2020-04-22 07:01 UTC, MikuroXina commented on src/comp/DevExperience.tsx
> +  const changeIntroductionStyle = (introduction: string) => {
```suggestion
  const omitIntroduction = (introduction: string) => {
```
こっちの方が短い

2020-04-22 07:17 UTC, MikuroXina requested changes
全部見直して気になったので追加します、すいません

2020-04-22 07:17 UTC, MikuroXina commented on src/comp/DevExperience.tsx
> +  const changeIntroductionStyle = (introduction: string) => {
```suggestion
  const omitIntroduction = (introduction: string) => {
```
こっちの方が短い

2020-04-22 07:17 UTC, MikuroXina commented on src/comp/DevExperience.tsx
> +  };
```suggestion
  const returnChipContents = (tagList: string[]) =>
    (
      <>
        {tagList.slice(0, 3).map((tag: string, i: number) => (
          <Chip
            className={styles.chip}
            variant="outlined"
            size="small"
            label={tag}
            key={i}
          />
        ))}
      </>
    )
```
`slice` を使って非破壊にしたい

2020-04-22 07:17 UTC, MikuroXina commented on src/comp/DevExperience.tsx
> +  };
```suggestion
  const projectData = () =>
    (
      projectDataList.slice(0, 4)
    )
```
`slice` を使って非破壊にしたい

2020-04-22 07:17 UTC, MikuroXina commented on src/comp/FollowButton.tsx
> +      {props.isFollowing ? <p>UnFollow</p> : <p>Follow</p>}
```suggestion
      {props.isFollowing ? <p>Unfollow</p> : <p>Follow</p>}
```
`UnFollow` じゃなくて `Unfollow` じゃないんすか

2020-04-22 08:01 UTC, MikuroXina approved these changes
流石にもう大丈夫でしょう(フラグ

2020-04-23 14:10 UTC, unios103 commented
マージしまーす
ありがとうございました

2020-04-23 14:11 UTC, merged