プロジェクト作成ページのコンテンツを増やして招待ページを作った
brokenManager/devlaza-front pull request #48
Opened 2020-05-05 04:37 UTC by loxygenK

<details><summary>プロジェクト作成ページ</summary>

![image](https://user-images.githubusercontent.com/55672846/81035191-e8502980-8ed4-11ea-8800-9a7c643f0f8d.png)

</details>

<details><summary>ユーザー招待ページ</summary>

<details><summary>候補非表示時</summary>

![image](https://user-images.githubusercontent.com/55672846/81035230-0cac0600-8ed5-11ea-9051-950fcaedd3bc.png)

</details>
<details><summary>候補表示時</summary>

![image](https://user-images.githubusercontent.com/55672846/81035267-35340000-8ed5-11ea-8a49-97c0f1f1b52e.png)

</details>

</details>

`src/css/comp/ScrollableTagList.module.css` ですごい無理やり実装してしまったので、解決策があれば教えてほしいです :bow:

2020-05-05 05:17 UTC, unios103 commented
今から見るのでちょっと待ってください

2020-05-05 05:54 UTC, unios103 requested changes
先にデザインについて（コードについては一切指摘していません）
- `/projects/create` 追加ボタンと `/projects/create/invite` のスキップは `outlined` にしてください
- 余白が一定ではない（デザインがそろっていない）のが気になります。できるだけ同じstyleをあてるようにしてください
- グループを明確にしてください。`タイトル〜追加` は要素間の余白を小さく取り、`タイトル〜追加` のグループの間の余白は大きくしてください。
- `サイトのURLは空白に出来ません` はなくていいと思います（追加しようとして止めることもあるため）
- `タグ` と `welcome!` のチップを追加する部分のデザインは同じにしてください（`タグ` を `welcome!` のデザインに合わせる）
- `Welcome!` 直下の説明文は左寄せにしてください。

2020-05-05 08:36 UTC, MikuroXina requested changes
テキトウ Request changes

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/ProjectTag.tsx
> +    );
```suggestion
    const name = `タグ: ${this.props.tag_id}`;
    return (
      <p className={styles.ptag_wrapper} onClick={this.props.onClick}>
        {name}
      </p>
    );
```
これ `setState` がどこにもないので状態を使う意味がないっすね

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/ProjectTag.tsx
> +  };
このくらいの `defaultProps` なら、
`onClick` が `== null` かどうかチェックして呼び出しても大丈夫そう

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/ProjectTag.tsx
> +  onClick: (e: React.MouseEvent<HTMLParagraphElement>) => void;
```suggestion
  onClick?: (e: React.MouseEvent<HTMLParagraphElement>) => void;
```
このままでは指定しないパターンを受け付けないのでは(憶測)

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/ScrollableTagList.tsx
> +  ) => void;
```suggestion
  onTagClick?: (
    tagID: string,
    e: React.MouseEvent<HTMLParagraphElement>
  ) => void;
```
指定しない場合を許容していないのでは(既視感)

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/SendButton.tsx
> +const CreateSendButton: React.FunctionComponent<SendButtonProps> = (props) => {
```suggestion
const CreateSendButton: React.FC<SendButtonProps> = (props) => {
```
`FC` の方がいいです

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/ScrollableTagList.tsx
> +  };
このくらいの `defaultProps` なら呼び出すところで `null` チェックでもいいのでは

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/UserInputField.tsx
> +        )}
ここは流石にネストが深すぎるので別の関数に分けましょう

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/UserInputField.tsx
> +};
`User` の型定義と API をぶっ叩く部分をまとめて別ファイルにしましょう

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/UserInputField.tsx
> +  private pendingRequestTimerId: number | null;
`componentWillUnmount` でも `clearTimeout` してください

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +  siteURLErrorCode: number;
```suggestion
  errors: ProjectError[],
```

以下のような型定義を作ってもっとわかりやすくしてほしいです

```
type ProjectError =
  | "name"
  | "introduction"
  | "siteName"
  | TagIDError
  | SiteURLError;
type TagIDErrpr = "blank" | "duplicate" | "unavailableChar";
type SiteURLError = "blank" | "invalid";

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +};
`Site` の型定義と実際に作成する API を叩く部分をまとめて別ファイルにしてほしいです

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +    }
`%2B` でエスケープできないんすか

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +    });
タグのリストの取得/管理は `TagList` みたいなクラスを作ってそっちでやらせたいです

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +    }
この辺のテキスト決定は、オブジェクトを辞書配列みたいに使えばきれいに書けそうです

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
> +            </div>
タグ、サイトの名前&URLがフラットに並んでますが、
タイトル、入力フォーム、追加ボタンのまとまりを別コンポーネントに分けませんか?

2020-05-05 08:36 UTC, MikuroXina commented on src/css/comp/ScrollableTagList.module.css
> +    height: 2.3rem;
```suggestion
    min-height: 2.3rem;
```
こうですかね(未検証)

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/UserInvitePage.tsx
> +  selectedUserId: string[];
```suggestion
  selectedUserIds: string[];
```
他は複数形だったのでここも複数形にしてほしい

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/pages/UserInvitePage.tsx
> +  isConfirmDialogOpen: boolean;
```suggestion
  openedConfirmDialog: boolean;
```
ちょっとわかりにくかったので、あくまで提案ですが

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/UserInputField.tsx
> +  suggestedUser: User[];
```suggestion
  suggestedUsers: User[];
```
複数形にしたい

2020-05-05 08:36 UTC, MikuroXina commented on src/comp/ProjectTag.tsx
>    tag_id: string;
```suggestion
  tagId: string;
```
なぜか `snake_case` になってた
できれば直しておいてください

2020-05-05 09:09 UTC, unios103 requested changes
すっごく自信のない***Request changes***

2020-05-05 09:09 UTC, unios103 commented on src/comp/pages/CreateProjectPage.tsx
> +              />
```tsx
import TextFieldTemplate, { TextFieldProps } from "@material-ui/core/TextField";
type TextFieldOriginalProps = {
  onChange?:() => void;
  error?:boolean;
  ...いろいろ
}
const TextField = (props: TextFieldProps&TextFieldOriginalProps) => {
  return (
    <TextFieldTemplate 
      {...props}
      margin="normal"
      multiline
      variant="outlined"
      fullWidth
    />
  );
};

...いろいろ

<TextField
  onChange={this.handleSiteNameChange}
  error={this.state.isSiteNameError}
/>
```
こんな感じにできるはずなので試してみてください。
（↓このコードで上のやり方が使われてます）
- [カスタマイズされたスナックバー](https://material-ui.com/ja/components/snackbars/#CustomizedSnackbars.tsx)

2020-05-05 10:47 UTC, unios103 requested changes
度々ごめんなさい

2020-05-05 10:47 UTC, unios103 commented on src/comp/pages/CreateProjectPage.tsx
> +              <Box m={1} />
css側でしてください、、、

2020-05-05 10:47 UTC, unios103 commented on src/comp/ScrollableTagList.tsx
> +        <div className={style.tag_list}>
```suggestion
      <>
```
他の項目と動作が同じになるようにした方がいいです

2020-05-05 10:47 UTC, unios103 commented on src/comp/pages/CreateProjectPage.tsx
> +                ))}
```suggestion
                {this.state.sites.map((site, index) => (
                  <Card variant="outlined" key={index}>
                    <ListItem>
                      <ListItemText primary={site.title} secondary={site.url} />
                      <ListItemSecondaryAction>
                        <IconButton
                          onClick={() => {
                            this.handleSiteRemoveButton(index);
                          }}
                        >
                          <CloseIcon />
                        </IconButton>
                      </ListItemSecondaryAction>
                    </ListItem>
                  </Card>
                ))}
```
- [Outlined Card](https://material-ui.com/ja/components/cards/#OutlinedCard.tsx)
デザインを合わせましょう

2020-05-05 10:47 UTC, unios103 commented on src/comp/pages/CreateProjectPage.tsx
> +  };
確認しなくていいです（もし確認が必要ならWelcome!ページでも確認するようにしてください）

2020-05-05 10:47 UTC, unios103 commented on src/comp/UserInputField.tsx
> +              />
`src/comp/ProjectTag.tsx` を使うようにできませんか（あと、テキストフィールド内に表示させないでタグの項目と同じ形式にしてください）

2020-05-05 10:47 UTC, unios103 commented on src/comp/pages/UserInvitePage.tsx
> +        </Dialog>
別コンポーネントにしましょう

2020-05-05 10:47 UTC, unios103 commented on src/comp/pages/UserInvitePage.tsx
> +        </div>
`招待する` と `スキップ` 逆の方がいいと思います

2020-05-06 06:52 UTC, loxygenK commented on src/comp/ProjectTag.tsx
> +    );
APIを叩いていたのがわかりにくかったので、`ComponentDidMount` にTODOを追加しておきました :bow:

2020-05-06 08:12 UTC, MikuroXina requested changes
重複する内容の Request Changes を省いたので前よりは控えめです

2020-05-06 08:12 UTC, MikuroXina commented on src/comp/ProjectTag.tsx
> +    });
末端のコンポーネントが API を叩くのはまずいですね
このコンポーネントは受け取ったラベルを表示するだけにして、
ページ側がタグのリストを取得して `map` するほうがきれいでしょう

2020-05-06 08:12 UTC, MikuroXina commented on src/comp/ScrollableTagList.tsx
> +                if (typeof this.props.onTagClick !== "undefined") {
```suggestion
                if (this.props.onTagClick != null) {
```
これでよくないっすか

2020-05-06 08:12 UTC, MikuroXina commented on src/comp/UserInputField.tsx
> +  };
`this` を使ってないので、クラスの外へただの関数として分けたほうがいいと思います
(`getOptionFromUser` も同じ)

2020-05-06 08:12 UTC, MikuroXina commented on src/comp/createProjPage/ProjectBasicInfoForm.tsx
> +    if (e.target.value.endsWith("\n")) return;
この方法だとコピーしてきた複数行のテキストを貼り付けられます

2020-05-06 08:12 UTC, MikuroXina commented on src/comp/createProjPage/ProjectBasicInfoForm.tsx
> +  };
`errors` という関数名にふさわしい操作じゃないですし、`isError` だと動作が分かりにくいです
`addError` と `removeError` に分けて、それぞれで `setState` したほうが良いと思います

2020-05-06 08:12 UTC, MikuroXina commented on src/utils/ValidationUtil.ts
> +export const checkIsUrl = (value: string) => !!value.match(/^https?:\/\/.+$/g);
```suggestion
export const checkIsUrl = (value: string) => /^https?:\/\/.+$/.test(value);
```
`test` を使いましょう
あと、`^` と `$` を使っているのにグローバル指定にしているのが正しいのか分からない

2020-05-06 08:12 UTC, MikuroXina commented on src/lib/util/TagList.ts
> +    }
```suggestion
  constructor(tags: Tag[] = []) {
    this.tagList = [...tags];
```
デフォルト引数のほうがいい気がする

2020-05-06 08:12 UTC, MikuroXina commented on src/lib/api/UserAPI.ts
> +  static async searchUserFromName(query: string): Promise<UserAPIResult> {
```suggestion
export namespace UserAPI {
  /**
   * 名前からユーザーを検索する。
   */
  export async function searchUserFromName(query: string): Promise<UserAPIResult> {
```
この目的なら `namespace` のほうがいいかも
(`TagAPI` など他の API 系も同様)

2020-05-06 08:12 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
>      }
```suggestion
    const creationTasks = this.state.sites.map((site) =>
      await SiteAPI.create(site.description, site.url, projectId)
    );
    await Promise.all(creationTasks);
```
これだと作成処理が一つずつ実行されるので、こうしてみたい
(あまり意味がないかもしれない)

2020-05-06 08:12 UTC, MikuroXina commented on src/comp/createProjPage/ProjectTagForm.tsx
> +    const isUserDecided = window.confirm(`本当に削除しますか?`);
こっちの確認ダイアログには Material UI のやつ使わないんですか

2020-05-10 10:50 UTC, loxygenK commented on src/comp/pages/CreateProjectPage.tsx
>      }
バックの人と話してみたんですが、`Promise.all`を使って並列でリクエストを送ってしまうとデータベース側でコンフリクトが発生するかもしれないそうです…
ひとまずここは変更せずに残しておきます :bow:

2020-05-10 10:53 UTC, MikuroXina commented on src/comp/pages/CreateProjectPage.tsx
>      }
👌

2020-05-10 12:01 UTC, MikuroXina requested changes

2020-05-10 12:01 UTC, MikuroXina commented on src/comp/createProjPage/ProjectBasicInfoForm.tsx
> +    if (e.target.value.indexOf("\n") !== -1) return;
```suggestion
    if (e.target.value.includes("\n")) return;
```
`includes` の方がいいと思います
他のところも同様に直してほしいです

2020-05-10 12:01 UTC, MikuroXina commented on src/lib/util/TagList.ts
>      if (typeof tags === "undefined") {
```suggestion
    if (tags == null) {
```
チェックするんだったらこうだと思う
TypeScript だから配列以外が来ないわけだしこの分岐自体が不要な気がするけれど

2020-05-10 12:55 UTC, MikuroXina requested changes
全部見直してラスト一個

2020-05-10 12:55 UTC, MikuroXina commented on src/comp/ListElementTag.tsx
> +    if (typeof this.props.imageUrl !== "undefined") {
```suggestion
    if (this.props.imageUrl != null) {
```
ここもこうしたい

2020-05-10 14:09 UTC, MikuroXina approved these changes

2020-05-10 14:17 UTC, unios103 requested changes
- プロジェクトの説明 *
- Welcome!ページの余白
を、直してください

2020-05-10 14:41 UTC, unios103 approved these changes
できれば１文字目から候補出して欲しいけど、、、
***Approve*** します！！！

2020-05-10 14:42 UTC, loxygenK commented
グワーーーッ！！！忘れてた！！！！！ごめんなさい！！！！！！！！111
やります

2020-05-10 14:59 UTC, unios103 requested changes
***ごめんなさい、、、***
これを直してください
![31007F69-993E-4DB5-8AAC-B1B297E85D9D_4_5005_c](https://user-images.githubusercontent.com/55628112/81502602-e5f92f80-9319-11ea-9a20-f29bb92eacf0.jpeg)
要素間に余白を入れるのと、urlが同じまたはサイト名が同じだった場合にエラー出してください
![13C106A5-3C90-4757-93BE-070FB5E615A8_4_5005_c](https://user-images.githubusercontent.com/55628112/81502607-e7c2f300-9319-11ea-8d04-4a8c03b6b120.jpeg)
これもタグ削除のときの動作と同じにしてください（確認いらないです）
![FACA2F06-46E2-47CC-8ECF-16872254B987_4_5005_c](https://user-images.githubusercontent.com/55628112/81502609-e85b8980-9319-11ea-8828-6edc8076257e.jpeg)
同じタグ名入れて**追加**押すと、そのあともerrorになって追加できなくなります

2020-05-11 07:10 UTC, unios103 commented
***追記***
---
１つ目の `要素間に余白を入れる` について

↓これを使うといいと思います
- [【CSS】フクロウセレクタ便利じゃん](https://t1y.me/owl-selector/)
> .class > * + * として直接の子要素を指定しているのですが、これを .class * + * のように子孫要素に指定することで、入れ子になっているリストなど階層構造になっていても適用することができます。

2020-05-16 06:29 UTC, loxygenK commented
`addError`と`removeError`の仕様変更を行いました (直接`this.setState`を叩くのをやめて`Reducer`みたいなことをするようにしました)

2020-05-16 07:04 UTC, MikuroXina requested changes

2020-05-16 07:04 UTC, MikuroXina commented on src/comp/UserInputField.tsx
> +    }
この判断を `UserAPI` 側でやるのはどうでしょうか

2020-05-16 07:04 UTC, MikuroXina commented on src/comp/createProjPage/ProjectSiteForm.tsx
> +    }
```suggestion
    const siteUrlHelperText = this.state.isUrlInvalid &&
      "正しい形式で入力されていません";
```
`let` を消したい

2020-05-16 07:04 UTC, MikuroXina commented on src/comp/createProjPage/ProjectBasicInfoForm.tsx
> +  private errorMessages: { [name in ErrorType]: string } = {
```suggestion
  private readonly errorMessages: { [name in ErrorType]: string } = {
```
`readonly` にするか、クラス外で定数として定義してほしいです

2020-05-16 07:04 UTC, MikuroXina commented on src/comp/createProjPage/ProjectBasicInfoForm.tsx
> +    }
`this.state.errors` を受け取って各テキストが入ったオブジェクトを返す
みたいな関数に分けたい

```
const { nameHelperText, introductionHelperText } =
  helperTexts(this.state.errors);
```
みたいに書けたら嬉しい

2020-05-16 07:04 UTC, MikuroXina commented on src/comp/createProjPage/ProjectTagForm.tsx
> +    }
```suggestion
    const tagIDHelperText = helperText(this.state.errors);
```
処理を関数に分けて、`let` を `const` にしたい

2020-05-17 06:51 UTC, MikuroXina approved these changes

2020-05-17 07:20 UTC, unios103 commented
**approve** してもいいんですけど１つだけ気になったことがあるので、、
タグが重複している時と、url（サイト名）が重複していた時の警告を出すタイミングを同じにすることはできませんか？
前者は追加ボタンを押した時、後者は打っている途中から警告がでます。

2020-05-17 07:21 UTC, loxygenK commented
追加しようとしたときに警告を出すように調整しますね:bow:

2020-05-17 07:34 UTC, unios103 approved these changes
とても良きです！！！天才！！！
***†Approve†***

2020-05-17 07:37 UTC, MikuroXina approved these changes

2020-05-17 08:45 UTC, merged